// <auto-generated />
#nullable enable
// generated by tool (64 key types + 16 miss types)
namespace BunnyTail.Resolver.Sandbox.Infrastructure;

public sealed class K000 { }
public sealed class K001 { }
public sealed class K002 { }
public sealed class K003 { }
public sealed class K004 { }
public sealed class K005 { }
public sealed class K006 { }
public sealed class K007 { }
public sealed class K008 { }
public sealed class K009 { }
public sealed class K010 { }
public sealed class K011 { }
public sealed class K012 { }
public sealed class K013 { }
public sealed class K014 { }
public sealed class K015 { }
public sealed class K016 { }
public sealed class K017 { }
public sealed class K018 { }
public sealed class K019 { }
public sealed class K020 { }
public sealed class K021 { }
public sealed class K022 { }
public sealed class K023 { }
public sealed class K024 { }
public sealed class K025 { }
public sealed class K026 { }
public sealed class K027 { }
public sealed class K028 { }
public sealed class K029 { }
public sealed class K030 { }
public sealed class K031 { }
public sealed class K032 { }
public sealed class K033 { }
public sealed class K034 { }
public sealed class K035 { }
public sealed class K036 { }
public sealed class K037 { }
public sealed class K038 { }
public sealed class K039 { }
public sealed class K040 { }
public sealed class K041 { }
public sealed class K042 { }
public sealed class K043 { }
public sealed class K044 { }
public sealed class K045 { }
public sealed class K046 { }
public sealed class K047 { }
public sealed class K048 { }
public sealed class K049 { }
public sealed class K050 { }
public sealed class K051 { }
public sealed class K052 { }
public sealed class K053 { }
public sealed class K054 { }
public sealed class K055 { }
public sealed class K056 { }
public sealed class K057 { }
public sealed class K058 { }
public sealed class K059 { }
public sealed class K060 { }
public sealed class K061 { }
public sealed class K062 { }
public sealed class K063 { }

public sealed class M000 { }
public sealed class M001 { }
public sealed class M002 { }
public sealed class M003 { }
public sealed class M004 { }
public sealed class M005 { }
public sealed class M006 { }
public sealed class M007 { }
public sealed class M008 { }
public sealed class M009 { }
public sealed class M010 { }
public sealed class M011 { }
public sealed class M012 { }
public sealed class M013 { }
public sealed class M014 { }
public sealed class M015 { }

public static class KeyTypes
{
    public static readonly Type[] All =
    [
        typeof(K000),
        typeof(K001),
        typeof(K002),
        typeof(K003),
        typeof(K004),
        typeof(K005),
        typeof(K006),
        typeof(K007),
        typeof(K008),
        typeof(K009),
        typeof(K010),
        typeof(K011),
        typeof(K012),
        typeof(K013),
        typeof(K014),
        typeof(K015),
        typeof(K016),
        typeof(K017),
        typeof(K018),
        typeof(K019),
        typeof(K020),
        typeof(K021),
        typeof(K022),
        typeof(K023),
        typeof(K024),
        typeof(K025),
        typeof(K026),
        typeof(K027),
        typeof(K028),
        typeof(K029),
        typeof(K030),
        typeof(K031),
        typeof(K032),
        typeof(K033),
        typeof(K034),
        typeof(K035),
        typeof(K036),
        typeof(K037),
        typeof(K038),
        typeof(K039),
        typeof(K040),
        typeof(K041),
        typeof(K042),
        typeof(K043),
        typeof(K044),
        typeof(K045),
        typeof(K046),
        typeof(K047),
        typeof(K048),
        typeof(K049),
        typeof(K050),
        typeof(K051),
        typeof(K052),
        typeof(K053),
        typeof(K054),
        typeof(K055),
        typeof(K056),
        typeof(K057),
        typeof(K058),
        typeof(K059),
        typeof(K060),
        typeof(K061),
        typeof(K062),
        typeof(K063),
    ];

    public static readonly Type[] Miss =
    [
        typeof(M000),
        typeof(M001),
        typeof(M002),
        typeof(M003),
        typeof(M004),
        typeof(M005),
        typeof(M006),
        typeof(M007),
        typeof(M008),
        typeof(M009),
        typeof(M010),
        typeof(M011),
        typeof(M012),
        typeof(M013),
        typeof(M014),
        typeof(M015),
    ];
}
